[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# include day16/main.rs into module tree
[[bin]]
name = "day16"
path = "day16/main.rs"

[dependencies]
